# Use official Node.js runtime as base image
FROM node:18-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
# RUN npm ci --only=production
# Si tienes un package-lock.json, también cópialo para instalaciones más rápidas y consistentes
COPY package-lock.json ./ 
RUN npm install --only=production

# Copy the source code
COPY . .

# Build the application
RUN npm run build

# Use official Nginx image as base
FROM nginx:alpine

# Copy the built application from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]