# Usa una imagen de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package.json .
COPY package-lock.json .

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto de desarrollo de React (3000)
EXPOSE 3000

# Inicia el servidor de desarrollo de React
CMD ["npm", "start"]
